"""Shared dashboard constants."""

from engram.models import MIN_ACTIVE_CONFIDENCE as _MIN_ACTIVE_CONFIDENCE

MIN_ACTIVE_CONFIDENCE = _MIN_ACTIVE_CONFIDENCE

NO_PROJECT_LABEL = "(none)"
REFRESH_INTERVAL = 5.0
SEARCH_DEBOUNCE_S = 0.15
UNDO_WINDOW_S = 10.0
