"""Project briefs: one compact orientation card per project.

A brief is an ordinary fact (``memory_key = "project-brief"``) regenerated by
upkeep whenever the project's other facts changed since the current brief was
written. The previous brief is superseded, so history stays in the event log.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timezone

from pydantic import BaseModel, ConfigDict

from engram.core.config import get_settings
from engram.core.models import Durability, Fact, FactCategory
from engram.llm import complete_model
from engram.maintenance.consolidate import BRIEF_KEY
from engram.maintenance.upkeep_report import StepReport
from engram.storage.store import AsyncFactStore, ChangeSet

logger = logging.getLogger(__name__)

BRIEF_SOURCE = "engram:brief"
MIN_FACTS_FOR_BRIEF = 5
MAX_BRIEF_INPUT_FACTS = 150

BRIEF_SYSTEM = """You write the project brief a coding agent reads before working in
a project. From the MEMORY CARDS, write at most 250 words as short sections with
these headings, omitting any section with nothing to say:

What it is / Conventions / Key workflows / Pitfalls / Open decisions

Name concrete commands, paths, and tools. Prefer durable rules over history. Use
only what the cards state; never invent. When cards conflict, the newer one wins.
retrieval_hints: 1-5 queries an agent might use to find this brief."""


class BriefResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    content: str
    retrieval_hints: list[str]


def _is_brief(fact: Fact) -> bool:
    return fact.memory_key == BRIEF_KEY


async def project_brief(store: AsyncFactStore, project: str) -> Fact | None:
    """The current brief card for ``project``, if one has been written."""
    facts = await store.load_active_facts(project=project, include_global=False)
    return next((fact for fact in facts if _is_brief(fact)), None)


def _brief_input(facts: list[Fact]) -> list[Fact]:
    """Durable knowledge first, then most recent, capped for one call."""
    rank = {Durability.evergreen: 0, Durability.durable: 0, Durability.ephemeral: 1}
    ordered = sorted(
        facts,
        key=lambda fact: (rank[fact.durability], -fact.observed_at.timestamp()),
    )
    return ordered[:MAX_BRIEF_INPUT_FACTS]


def _brief_prompt(project: str, facts: list[Fact]) -> str:
    lines = [
        f"- [{fact.category.value} · {fact.observed_at.date().isoformat()}] "
        f"{fact.content}"
        for fact in facts
    ]
    return f"PROJECT: {project}\n\nMEMORY CARDS:\n" + "\n".join(lines)


def _needs_brief(facts: list[Fact], previous: Fact | None) -> bool:
    if len(facts) < MIN_FACTS_FOR_BRIEF:
        return False
    if previous is None:
        return True
    return any(
        max(fact.created_at, fact.updated_at) > previous.created_at for fact in facts
    )


async def run_briefs(
    store: AsyncFactStore,
    *,
    project: str | None,
    report: StepReport,
    dry_run: bool,
    now: datetime,
) -> None:
    """Write or refresh briefs for every project whose facts changed."""
    settings = get_settings()
    # Taken before reading: facts written after this trigger the next refresh.
    snapshot = max(now, datetime.now(timezone.utc))
    facts = await store.load_active_facts(project=project, include_global=False)
    by_project: dict[str, list[Fact]] = {}
    # Newest first (load order); more than one only after a concurrent write.
    previous: dict[str, list[Fact]] = {}
    for fact in facts:
        if not fact.project:
            continue
        if _is_brief(fact):
            previous.setdefault(fact.project, []).append(fact)
        else:
            by_project.setdefault(fact.project, []).append(fact)

    targets = [
        name
        for name, project_facts in sorted(by_project.items())
        if len(previous.get(name, [])) > 1
        or _needs_brief(project_facts, next(iter(previous.get(name, [])), None))
    ]
    report.bump("projects", len(targets))
    semaphore = asyncio.Semaphore(max(1, settings.maintenance_concurrency))

    async def refresh(name: str) -> None:
        inputs = _brief_input(by_project[name])
        async with semaphore:
            report.llm_calls += 1
            try:
                response = await complete_model(
                    _brief_prompt(name, inputs),
                    system=BRIEF_SYSTEM,
                    response_model=BriefResponse,
                    reasoning_effort=settings.llm_reasoning_effort,
                )
            except Exception as exc:  # noqa: BLE001 - one project must not stop upkeep
                report.errors.append(f"{name}: brief failed ({exc})")
                return
        olds = previous.get(name, [])
        brief = Fact(
            category=FactCategory.project,
            memory_key=BRIEF_KEY,
            content=response.content.strip(),
            source=BRIEF_SOURCE,
            created_at=snapshot,
            updated_at=snapshot,
            observed_at=snapshot,
            tags=["brief"],
            retrieval_hints=list(dict.fromkeys(response.retrieval_hints))[:5]
            or [f"{name} project overview"],
            project=name,
            supersedes=olds[0].id if olds else None,
            why_store="Orientation summary of the project's memories",
            durability=Durability.durable,
        )
        changes = ChangeSet(
            new_facts=[brief],
            supersede={old.id: brief.id for old in olds},
            expected={old.id: old.updated_at for old in olds},
            reason="upkeep: project brief refreshed",
            actor=BRIEF_SOURCE,
        )
        if not dry_run:
            result = await store.apply_changes(changes, all_or_nothing=True)
            if result.skipped:
                report.errors.append(f"{name}: previous brief changed concurrently")
                return
        report.add("created", brief.id)
        report.add("superseded", *(old.id for old in olds))

    await asyncio.gather(*(refresh(name) for name in targets))
    if dry_run and targets:
        report.notes.insert(0, "dry run: LLM was called, nothing applied")
